miurahr/pyppmd

- src/cffi/cffi_ppmd.py
- src/ext/_ppmdmodule.c
- src/ext/ffi_build.py
- tests/test_ppmd7.py
- tests/test_ppmd7_fuzzer.py
> Introduce Decoder.flush

- tests/test_benchmark.py
- utils/bench_result.py
> CFFI: PPMd8: enable benchmark

- src/pyppmd/cffi/cffi_ppmd.py
> Close resources when flush()

- src/ext/_ppmdmodule.c
> C: Allow python threads during encode/decode

- README.rst
> added conda recipe #18

- .github/workflows/cibuildwheel.yml
> GHA: --egg-base is global option of setup.py

- CMakeLists.txt
- lib/Ppmd.h
- lib/Ppmd7Enc.c
Ref: https://github.com/miurahr/pyppmd/security/code-scanning/1
> Security hardening

- CMakeLists.txt
> CMake: add generate_ext as pytest_runner dependency

- CMakeLists.txt
- setup.py
> CMake: add debug flag for extension build

- src/ext/ffi_build.py
> cffi: fix macOS pthread_t definition

- CMakeLists.txt
> CMake: Add  pypy pytest runner

- src/ext/_ppmdmodule.c
> Replace direct value to symbol

- CMakeLists.txt
> Cmake: improve pytest_runner

- src/ext/_ppmdmodule.c
> ppmd8dec: use PyMem for in/out buffers in init

- lib2/threading.c
Hopefully will fix #49 but this needs to be tested since I don't have a mac machine.
> fix for osx compilation

- .github/workflows/run-tox-tests.yml
> CI: add macos for test matrix

- lib2/Ppmd8Tdecoder.c
- lib2/Ppmd8Tdecoder.h
- src/ext/_ppmdmodule.c
- src/ext/ffi_build.py
> ppmd8dec:  add ppmd8 prefix for threading globals

- src/ext/_ppmdmodule.c
avoid auto variables for threading
> ppmd7dec: Use PyMalloc for in/out buffer memory

- CMakeLists.txt
> CMake: Update pypy test code

- tests/test_ppmd8.py
> ppmd8: use eof flag for decompress test

- src/pyppmd/__init__.py
- tests/test_ppmd8.py
> Support unified API

- docs/api_guide.rst
- docs/authors.rst
- docs/index.rst
- docs/ppmd7.rst
- docs/ppmd8.rst
> docs: update api docs

- src/ext/_ppmdmodule.c
> Ppmd7Decoder_dealloc: guard PyMem_Free from NULL

- docs/ppmd7.rst
- docs/ppmd8.rst
- src/ext/_ppmdmodule.c
- src/ext/ffi_build.py
- src/pyppmd/cffi/cffi_ppmd.py
- tests/test_ppmd7.py
- tests/test_ppmd8.py
> Introduce endmark: boolean for flush() methods

- src/ext/_ppmdmodule.c
- src/ext/ffi_build.py
- src/pyppmd/cffi/cffi_ppmd.py
- tests/test_ppmd7.py
> PPMd7 decoder checks return value of DecodeSymbol func

- .github/workflows/run-tox-tests.yml
- lib2/ThreadDecoder.c
> Fix build on MSYS2/Mingw

- .github/dependabot.yml
- .github/workflows/cibuildwheel.yml
> CI: use pypa/cibuidwheel action

- .github/workflows/cibuildwheel.yml
- pyproject.toml
> Set cibuildwheel configurations on pyproject.toml

- tests/test_benchmark.py
- tests/test_fuzzer.py
- tests/test_ppmd7.py
> Update fuzzer test logic

- lib2/Buffer.h
- lib2/ThreadDecoder.c
- lib2/ThreadDecoder.h
- src/ext/_ppmdmodule.c
- src/ext/ffi_build.py
- src/pyppmd/cffi/cffi_ppmd.py
- tests/test_benchmark.py
- tests/test_fuzzer.py
- tests/test_ppmd7.py
- Add Ppmd7T_decode function
- Change tests
- Fuzzer test with various text
> thread decode on ppmd7

- .github/workflows/run-tox-tests.yml
- Add test on Python 3.7 (x86) on windows 
- Change action name
> Actions: tox test with python 3.7(x86) on windows

- src/ext/_ppmdmodule.c
> Check NULL before free self->rangeDec members

- pyproject.toml
- setup.cfg
> pyproject.toml: update project section

- src/ext/_ppmdmodule.c
> PPMd8: check double flush

- .github/workflows/codeql-analysis.yml
> Actions: codeql: setup python3 for build

- .github/workflows/cibuildwheel.yml
- .github/workflows/run-tox-tests.yml
> Actions: update setuptools before run tox
